import { BibleBook } from './types';

export const BIBLE_BOOKS: BibleBook[] = [
  // Old Testament
  { id: 'genesis', name: 'سفر التكوين', chapters: 50 },
  { id: 'exodus', name: 'سفر الخروج', chapters: 40 },
  { id: 'leviticus', name: 'سفر اللاويين', chapters: 27 },
  { id: 'numbers', name: 'سفر العدد', chapters: 36 },
  { id: 'deuteronomy', name: 'سفر التثنية', chapters: 34 },
  { id: 'joshua', name: 'سفر يشوع', chapters: 24 },
  { id: 'judges', name: 'سفر القضاة', chapters: 21 },
  { id: 'ruth', name: 'سفر راعوث', chapters: 4 },
  { id: '1samuel', name: 'سفر صموئيل الأول', chapters: 31 },
  { id: '2samuel', name: 'سفر صموئيل الثاني', chapters: 24 },
  { id: '1kings', name: 'سفر الملوك الأول', chapters: 22 },
  { id: '2kings', name: 'سفر الملوك الثاني', chapters: 25 },
  { id: '1chronicles', name: 'سفر أخبار الأيام الأول', chapters: 29 },
  { id: '2chronicles', name: 'سفر أخبار الأيام الثاني', chapters: 36 },
  { id: 'ezra', name: 'سفر عزرا', chapters: 10 },
  { id: 'nehemiah', name: 'سفر نحميا', chapters: 13 },
  { id: 'esther', name: 'سفر أستير', chapters: 10 },
  { id: 'job', name: 'سفر أيوب', chapters: 42 },
  { id: 'psalms', name: 'سفر المزامير', chapters: 150 },
  { id: 'proverbs', name: 'سفر الأمثال', chapters: 31 },
  { id: 'ecclesiastes', name: 'سفر الجامعة', chapters: 12 },
  { id: 'songofsolomon', name: 'نشيد الأنشاد', chapters: 8 },
  { id: 'isaiah', name: 'سفر إشعياء', chapters: 66 },
  { id: 'jeremiah', name: 'سفر إرميا', chapters: 52 },
  { id: 'lamentations', name: 'مراثي إرميا', chapters: 5 },
  { id: 'ezekiel', name: 'سفر حزقيال', chapters: 48 },
  { id: 'daniel', name: 'سفر دانيال', chapters: 12 },
  { id: 'hosea', name: 'سفر هوشع', chapters: 14 },
  { id: 'joel', name: 'سفر يوئيل', chapters: 3 },
  { id: 'amos', name: 'سفر عاموس', chapters: 9 },
  { id: 'obadiah', name: 'سفر عوبديا', chapters: 1 },
  { id: 'jonah', name: 'سفر يونان', chapters: 4 },
  { id: 'micah', name: 'سفر ميخا', chapters: 7 },
  { id: 'nahum', name: 'سفر ناحوم', chapters: 3 },
  { id: 'habakkuk', name: 'سفر حبقوق', chapters: 3 },
  { id: 'zephaniah', name: 'سفر صفنيا', chapters: 3 },
  { id: 'haggai', name: 'سفر حجي', chapters: 2 },
  { id: 'zechariah', name: 'سفر زكريا', chapters: 14 },
  { id: 'malachi', name: 'سفر ملاخي', chapters: 4 },

  // Deuterocanonical Books (الأسفار المحذوفة)
  { id: 'tobit', name: 'سفر طوبيا', chapters: 14 },
  { id: 'judith', name: 'سفر يهوديت', chapters: 16 },
  { id: 'est_additions', name: 'تتمة أستير', chapters: 6 }, // Often viewed as chapters 11-16
  { id: 'wisdom', name: 'سفر الحكمة', chapters: 19 },
  { id: 'sirach', name: 'سفر يشوع بن سيراخ', chapters: 51 },
  { id: 'baruch', name: 'سفر باروخ', chapters: 6 },
  { id: 'dan_additions', name: 'تتمة دانيال', chapters: 2 }, // Chapters 13 & 14
  { id: '1maccabees', name: 'سفر المكابيين الأول', chapters: 16 },
  { id: '2maccabees', name: 'سفر المكابيين الثاني', chapters: 15 },

  // New Testament
  { id: 'matthew', name: 'إنجيل متى', chapters: 28 },
  { id: 'mark', name: 'إنجيل مرقس', chapters: 16 },
  { id: 'luke', name: 'إنجيل لوقا', chapters: 24 },
  { id: 'john', name: 'إنجيل يوحنا', chapters: 21 },
  { id: 'acts', name: 'أعمال الرسل', chapters: 28 },
  { id: 'romans', name: 'رومية', chapters: 16 },
  { id: '1corinthians', name: 'كورنثوس الأولى', chapters: 16 },
  { id: '2corinthians', name: 'كورنثوس الثانية', chapters: 13 },
  { id: 'galatians', name: 'غلاطية', chapters: 6 },
  { id: 'ephesians', name: 'أفسس', chapters: 6 },
  { id: 'philippians', name: 'فيلبي', chapters: 4 },
  { id: 'colossians', name: 'كولوسي', chapters: 4 },
  { id: '1thessalonians', name: 'تسالونيكي الأولى', chapters: 5 },
  { id: '2thessalonians', name: 'تسالونيكي الثانية', chapters: 3 },
  { id: '1timothy', name: 'تيموثاوس الأولى', chapters: 6 },
  { id: '2timothy', name: 'تيموثاوس الثانية', chapters: 4 },
  { id: 'titus', name: 'تيطس', chapters: 3 },
  { id: 'philemon', name: 'فليمون', chapters: 1 },
  { id: 'hebrews', name: 'العبرانيين', chapters: 13 },
  { id: 'james', name: 'يعقوب', chapters: 5 },
  { id: '1peter', name: 'بطرس الأولى', chapters: 5 },
  { id: '2peter', name: 'بطرس الثانية', chapters: 3 },
  { id: '1john', name: 'يوحنا الأولى', chapters: 5 },
  { id: '2john', name: 'يوحنا الثانية', chapters: 1 },
  { id: '3john', name: 'يوحنا الثالثة', chapters: 1 },
  { id: 'jude', name: 'يهوذا', chapters: 1 },
  { id: 'revelation', name: 'سفر الرؤيا', chapters: 22 },
];